export const alertatypes = {
    MOSTRAR_ALERTA:'MOSTRAR_ALERTA',
    CERRAR_ALERTA : 'CERRAR_ALERTA',
}

export const emailTypes = {
    SEND_CONTACT_EMAIL : 'SEND_CONTACT_EMAIL', 
    SEND_CONTACT_EMAIL_STATUS : 'SEND_CONTACT_EMAIL_STATUS', 
}